#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : jack2
Version  : 1.9.14
Release  : 5
URL      : file:///insilications/build/clearlinux/packages/jack2/jack2-v1.9.14.zip
Source0  : file:///insilications/build/clearlinux/packages/jack2/jack2-v1.9.14.zip
Summary  : the Jack Audio Connection Kit: a low-latency synchronous callback-based media server
Group    : Development/Tools
License  : GPL-3.0
Requires: jack2-bin = %{version}-%{release}
Requires: jack2-data = %{version}-%{release}
Requires: jack2-lib = %{version}-%{release}
Requires: jack2-man = %{version}-%{release}
Requires: jack2-services = %{version}-%{release}
Requires: ncurses
Requires: ncurses-dev
Requires: ncurses-lib
BuildRequires : alsa-firmware
BuildRequires : alsa-lib
BuildRequires : alsa-lib-bin
BuildRequires : alsa-lib-dev
BuildRequires : alsa-plugins
BuildRequires : alsa-tools
BuildRequires : alsa-tools-bin
BuildRequires : alsa-tools-dev
BuildRequires : alsa-ucm-conf
BuildRequires : alsa-utils
BuildRequires : alsa-utils-autostart
BuildRequires : alsa-utils-bin
BuildRequires : alsa-utils-config
BuildRequires : alsa-utils-services
BuildRequires : dbus-dev
BuildRequires : eigen
BuildRequires : eigen-dev
BuildRequires : expat-dev
BuildRequires : findutils
BuildRequires : libffado
BuildRequires : libffado-config
BuildRequires : libffado-data
BuildRequires : libffado-dev
BuildRequires : libffado-lib
BuildRequires : libffado-python
BuildRequires : libffado-python3
BuildRequires : libsamplerate-dev
BuildRequires : libsndfile-dev
BuildRequires : ncurses
BuildRequires : ncurses-dev
BuildRequires : ncurses-lib
BuildRequires : opus-dev
BuildRequires : opus-staticdev
BuildRequires : pkg-config
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(alsa-topology)
BuildRequires : pkgconfig(eigen3)
BuildRequires : pkgconfig(libffado)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(ncursesw)
BuildRequires : pkgconfig(opus)
BuildRequires : pkgconfig(portaudio-2.0)
BuildRequires : pkgconfig(readline)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(tinfo)
BuildRequires : pkgconfig(tinfow)
BuildRequires : pkgconfig(udev)
BuildRequires : readline
BuildRequires : readline-dev
BuildRequires : readline-lib
BuildRequires : readline-staticdev
BuildRequires : systemd-dev
Patch1: 0002-Makefile-quick-wrapper-for-waf.patch

%description
-------------------------------
JACK2 on Windows
-------------------------------

%package bin
Summary: bin components for the jack2 package.
Group: Binaries
Requires: jack2-data = %{version}-%{release}
Requires: jack2-services = %{version}-%{release}

%description bin
bin components for the jack2 package.


%package data
Summary: data components for the jack2 package.
Group: Data

%description data
data components for the jack2 package.


%package dev
Summary: dev components for the jack2 package.
Group: Development
Requires: jack2-lib = %{version}-%{release}
Requires: jack2-bin = %{version}-%{release}
Requires: jack2-data = %{version}-%{release}
Provides: jack2-devel = %{version}-%{release}
Requires: jack2 = %{version}-%{release}

%description dev
dev components for the jack2 package.


%package lib
Summary: lib components for the jack2 package.
Group: Libraries
Requires: jack2-data = %{version}-%{release}

%description lib
lib components for the jack2 package.


%package man
Summary: man components for the jack2 package.
Group: Default

%description man
man components for the jack2 package.


%package services
Summary: services components for the jack2 package.
Group: Systemd services

%description services
services components for the jack2 package.


%prep
%setup -q -n jack2-v1.9.14
cd %{_builddir}/jack2-v1.9.14
%patch1 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1595846220
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden
# gcc: -feliminate-unused-debug-types -fipa-pta -Wno-error -Wp,-D_REENTRANT -fno-common  -fno-plt -fno-semantic-interposition  -flto=16
export CXXFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe"
#
export FCFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
export FFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
export CFFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
#
export LDFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#export CCACHE_DISABLE=1
## altflags1 end
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1595846220
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/alsa_in
/usr/bin/alsa_out
/usr/bin/jack_alias
/usr/bin/jack_bufsize
/usr/bin/jack_connect
/usr/bin/jack_control
/usr/bin/jack_cpu
/usr/bin/jack_cpu_load
/usr/bin/jack_disconnect
/usr/bin/jack_evmon
/usr/bin/jack_freewheel
/usr/bin/jack_iodelay
/usr/bin/jack_latent_client
/usr/bin/jack_load
/usr/bin/jack_lsp
/usr/bin/jack_metro
/usr/bin/jack_midi_dump
/usr/bin/jack_midi_latency_test
/usr/bin/jack_midiseq
/usr/bin/jack_midisine
/usr/bin/jack_monitor_client
/usr/bin/jack_multiple_metro
/usr/bin/jack_net_master
/usr/bin/jack_net_slave
/usr/bin/jack_netsource
/usr/bin/jack_property
/usr/bin/jack_rec
/usr/bin/jack_samplerate
/usr/bin/jack_server_control
/usr/bin/jack_session_notify
/usr/bin/jack_showtime
/usr/bin/jack_simdtests
/usr/bin/jack_simple_client
/usr/bin/jack_simple_session_client
/usr/bin/jack_test
/usr/bin/jack_thru
/usr/bin/jack_transport
/usr/bin/jack_unload
/usr/bin/jack_wait
/usr/bin/jack_zombie
/usr/bin/jackd
/usr/bin/jackdbus

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/services/org.jackaudio.service

%files dev
%defattr(-,root,root,-)
/usr/include/jack/control.h
/usr/include/jack/intclient.h
/usr/include/jack/jack.h
/usr/include/jack/jslist.h
/usr/include/jack/metadata.h
/usr/include/jack/midiport.h
/usr/include/jack/net.h
/usr/include/jack/ringbuffer.h
/usr/include/jack/session.h
/usr/include/jack/statistics.h
/usr/include/jack/systemdeps.h
/usr/include/jack/thread.h
/usr/include/jack/transport.h
/usr/include/jack/types.h
/usr/include/jack/uuid.h
/usr/include/jack/weakjack.h
/usr/include/jack/weakmacros.h
/usr/lib64/libjack.so
/usr/lib64/libjacknet.so
/usr/lib64/libjackserver.so
/usr/lib64/pkgconfig/jack.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/jack/audioadapter.so
/usr/lib64/jack/inprocess.so
/usr/lib64/jack/jack_alsa.so
/usr/lib64/jack/jack_alsarawmidi.so
/usr/lib64/jack/jack_dummy.so
/usr/lib64/jack/jack_firewire.so
/usr/lib64/jack/jack_loopback.so
/usr/lib64/jack/jack_net.so
/usr/lib64/jack/jack_netone.so
/usr/lib64/jack/jack_proxy.so
/usr/lib64/jack/netadapter.so
/usr/lib64/jack/netmanager.so
/usr/lib64/jack/profiler.so
/usr/lib64/libjack.so.0
/usr/lib64/libjack.so.0.1.0
/usr/lib64/libjacknet.so.0
/usr/lib64/libjacknet.so.0.1.0
/usr/lib64/libjackserver.so.0
/usr/lib64/libjackserver.so.0.1.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/alsa_in.1
/usr/share/man/man1/alsa_out.1
/usr/share/man/man1/jack_bufsize.1
/usr/share/man/man1/jack_connect.1
/usr/share/man/man1/jack_disconnect.1
/usr/share/man/man1/jack_freewheel.1
/usr/share/man/man1/jack_impulse_grabber.1
/usr/share/man/man1/jack_iodelay.1
/usr/share/man/man1/jack_load.1
/usr/share/man/man1/jack_lsp.1
/usr/share/man/man1/jack_metro.1
/usr/share/man/man1/jack_monitor_client.1
/usr/share/man/man1/jack_netsource.1
/usr/share/man/man1/jack_property.1
/usr/share/man/man1/jack_samplerate.1
/usr/share/man/man1/jack_showtime.1
/usr/share/man/man1/jack_simple_client.1
/usr/share/man/man1/jack_transport.1
/usr/share/man/man1/jack_unload.1
/usr/share/man/man1/jack_wait.1
/usr/share/man/man1/jackd.1
/usr/share/man/man1/jackrec.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/jack@.service
